---
- name: Collect cluster status
  hosts: db-group
  become: true

  tasks:
    - name: Check hostname
      command: hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout

    - name: Check DB2 services
      shell: |
        ps -ef | grep db2sysc | grep -v grep
      register: db2_status
      ignore_errors: true

    - debug:
        var: db2_status.stdout_lines
