---
- name: Generate Cluster Health Report
  hosts: db-group
  become: true
  gather_facts: false

  tasks:

    - name: Capture cluster status
      command: pcs status
      register: pcs_status

    - name: Save report
      copy:
        content: "{{ pcs_status.stdout }}"
        dest: /tmp/db2_cluster_report.txt
