---
- name: Detect DB2 Active and Passive Nodes
  hosts: db-group
  gather_facts: false
  become: true

  tasks:

    - name: Get cluster status
      command: crm_mon -1
      register: crm_status
      changed_when: false
      run_once: true

    - name: Extract active node
      set_fact:
        active_node: "{{ crm_status.stdout | regex_search('Masters: \\[ (.*?) \\]', '\\1') | first }}"
      run_once: true

    - name: Determine passive node
      set_fact:
        passive_node: >-
          {{
            groups['db-group']
            | difference([active_node])
            | first
          }}
      run_once: true

    - name: Display cluster roles
      debug:
        msg:
          - "Active Node : {{ active_node }}"
          - "Passive Node: {{ passive_node }}"
      run_once: true

    - name: Export workflow variables
      set_stats:
        data:
          active_node: "{{ active_node }}"
          passive_node: "{{ passive_node }}"
      run_once: true
