---
- name: DB2 Cluster Monitoring

  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Test Rule

      condition: event.payload.test == "hello"

      action:
        debug:
          msg: "Webhook matched"
